### ISSUE TITLE
Issue with "omero_import" tool - Images are not uploaded sequentially

### ISSUE THREAD

**Issue by rmassei** [Helmholtz-UFZ/galaxy-tools#70]
I noticed that when uploading images using the "omero_import" tool, images are not imported into OMERO according to the collection order.
For example, if I try to upload collection with the datasets:
```
- 87-H-03_ome.tif
- 89-H-05_ome.tif
- 90-H-06_ome.tif
```
They will be uploaded into OMERO in the following order:
```
- 90-H-06_ome.tif
- 87-H-03_ome.tif
- 89-H-05_ome.tif
```
I also tried with other file naming and I always obtained a random upload order. 
This might be a problem in a workflow containing per-processing image analysis step and the user want to attach results to image sequentially uploaded into OMERO.

Could this be a consequence on how we loop the images in the new directory "folder"? @bernt-matthias  @lldelisle 

https://github.com/Helmholtz-UFZ/galaxy-tools/blob/3c8e23e1dea22f625fb6f77ae61e1f4b605aaae2/tools/omero/omero_import.xml#L11-L19

**Comment by lldelisle** [comment]
Hi @rmassei ,
I think this is due to omero and we cannot really control this except uploading one image at a time but I don't think it is a good idea. Nobody should rely on image order on omero. I think the best way is to get image ids from omero. You can get them by parsing the log file.

**Comment by bernt-matthias** [comment]
I agree with @lldelisle that WFs should work independent of any ordering issues. 

But the ordering is still strange. Let me ask.

**Comment by rmassei** [comment]
Hi!
@lldelisle I managed to solve it in the workflow by paring the log file together with the omero_get_id :) it is nice to test and discover that the tool can also used to solve this little tricky things within the workflow!
@bernt-matthias I also thing that the ordering is strange, I normally get them in the same folder order when I import them using the OMERO cli

**Comment by bernt-matthias** [comment]
Now I get it. The symlinks will be created in the folder `./folder/` in the order specified in the collection. But the `omero import` will iterate over them in whichever order .. which we can not control. Maybe we could prefix the symlinks with the collection index 

```
#for $idx, $image in enumerate($folder): 
             #set image = $image 
             #set image_identifier = re.sub('[^\s\w\-]', '_', str($image.element_identifier)) 
             ln -s '${image}' folder/${index}_'${image_identifier}.$image.ext' && 
         #end for 
```

But as @lldelisle said we should not rely on the order anyway. So I would leave it as is.
